DROP TABLE IF EXISTS matches;
CREATE TABLE matches (
  match_id int PRIMARY KEY,
  balls_per_over int,
  match_city text,
  match_start_date date,
  match_year int,
  match_dates text,
  event_name text,
  match_number int,
  sub_name text,
  event_group text,
  event_stage text,
  info_missing text,
  super_subs text,
  match_gender text,
  match_type text,
  match_type_number int,
  officials_referees text,
  officials_tv_umpires text,
  officials_umpires text,
  match_result text,
  winning_team text,
  outcome_by text,
  outcome_eliminator text,
  is_dl boolean,
  is_tie boolean,
  outcome_result text,
  runs_won_by int,
  wickets_won_by int,
  overs int,
  player_of_match text,
  season text,
  team_type text,
  team_1 text,
  team_2 text,
  toss_decision text,
  toss_winner text,
  match_venue text,
  load_to_db_timestamp
);
