insert into matches
select
  match_id,
  info ->> 'balls_per_over' as balls_per_over,
  info ->> 'city' as match_city,
  date(info -> 'dates' ->> 0) as match_start_date,
  strftime('%Y', info -> 'dates' ->> 0) as match_year,
  info ->> 'dates' as match_dates,
  info -> 'event' ->> 'name' as event_name,
  info -> 'event' ->> 'match_number' as match_number,
  info -> 'event' ->> 'sub_name' as sub_name,
  info -> 'supersubs' as super_subs,
  info ->> 'gender' as match_gender,
  info ->> 'match_type' as match_type,
  info ->> 'match_type_number' as match_type_number,
  info -> 'officials' -> 'match_referees' as officials_referees,
  info -> 'officials' -> 'tv_umpires' as officials_tv_umpires,
  info -> 'officials' -> 'umpires' as officials_umpires,
  coalesce(info -> 'outcome' ->> 'result', 'winner decided') as match_result,
  info -> 'outcome' ->> 'winner' as winning_team,
  info -> 'outcome' ->> 'by' as outcome_by,
  info -> 'outcome' ->> 'eliminator' as outcome_eliminator,
  case when info -> 'outcome' ->> 'method' = 'D/L' then true else false end as is_dl,
  case when info -> 'outcome' ->> 'result' = 'tie' then true else false end as is_tie,
  info -> 'outcome' ->> 'result' as outcome_result,
  info -> 'outcome' -> 'by' ->> 'runs' as runs_won_by,
  info -> 'outcome' -> 'by' ->> 'wickets' as wickets_won_by,
  info ->> 'overs' as overs,
  info -> 'player_of_match' ->> 0 as player_of_match,
  info ->> 'season' as season,
  info ->> 'team_type' as team_type,
  info -> 'teams' ->> 0 as team_1,
  info -> 'teams' ->> 1 as team_2,
  info -> 'toss' ->> 'decision' as toss_decision,
  info -> 'toss' ->> 'winner' as toss_winner,
  info ->> 'venue' as match_venue,
  current_timestamp as load_to_db_timestamp
from
  load_match_data
;
